### ISSUE TITLE
SandBox

### ISSUE THREAD

**Issue by whera** [andrebian/cake-plugin-pagseguro#11]
Estou alterando as urls do caminho app/Plugin/vendor/pagseguro/php/source/PagSeguroLibrary/resources/PagSeguroResources.php para as urls definidas pelo PagSeguro para usar o sandbox deles, mais o sistema aplica as modificações.
existe algum outro lugar para alterar?

**Comment by andrebian** [comment]
Pronto, o plugin já está portado para trabalhar com o ambiente sandbox para os seguintes itens:

 - Requisição de pagamento
 - Retorno
 - Notificações

**Comment by danilofla** [comment]
Show de bola, começarei a testar em breve.

On Thursday, January 1, 2015, Andre Cardoso <notifications@github.com>
wrote:

> Pronto, o plugin já está portado para trabalhar com o ambiente sandbox
> para os seguintes itens:
>
>    - Requisição de pagamento
>    - Retorno
>    - Notificações
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrebian/cake-plugin-pagseguro/issues/11#issuecomment-68500462>
> .
>


-- 
Atenciosamente,
Danilo Santos.
Desenvolvedor Web

Enviado via Iphone!

**Comment by danilofla** [comment]
@andrebian Voltando aqui depois de tanto tempo, fiz vários testes locais utilizando a sandbox e foi tudo tranquilo, passei um tempo sem mexer na aplicação, quando coloquei no servidor e fui testar ainda com a sandbox, está retornando erro "[HTTP 401] - UNAUTHORIZED" novamente.

Tens idéia do que seja? O token está certinho, e-mail também.

Obs.: Esse erro dá no retorno do pagamento, ou seja, completo o pagamento com eles, mas na hora que retorna pro meu sistema, dá isso.

Obrigado.

**Comment by danilosantosdev** [comment]
Imprimir Boleto 6002842.rar467 KB Visualizar   Baixar 
      
 
Prezado Senhor:
Com o presente,tomamos a liberdade de lembrar que o titulo de seu aceite venceu em 28/09/2015.
Na certeza de suas providências para o seu resgate, segue o boleto para pagamento com vencimento dia 09/10/2015
Antecipamos os nossos agradecimentos, e subscrevemos-nos.
Atenciosamente,Associação dos Advogados de São Paulo AASP.
Dr. Helena Couto ColacioLocalização Rua: Álvares Penteado, 151 - Centro - São Paulo - CEP: 01012-905Telefone: (11) 3522-5711

**Comment by andrebian** [comment]
O que é isso @danilosantosdev ?

**Comment by danilosantosdev** [comment]
@andrebian Oxe velho, que doidera é essa? Não fui eu man ...

**Comment by andrebian** [comment]
Virge, que maluco ha ha ha

**Comment by danilosantosdev** [comment]
Serviço de entrega dos correios realizou uma tentativa  de entrega na 
data de 06/01/2015 não obtendo sucesso. Sera realizaodo  mais duas 
tentantivas de entrega .Para acompanhar seu pedido acesse o link abaixo e veja 
seu código de rastreamento.
Código_de_Rastreamento.zip
Após visualizar seu código de rastreamento acesse o site http://www2.correios.com.br/sistemas/rastreamento/ para 
efetuar o rastreamento.
Atenciosamente;Andre NunesResponsavel Pelo Setor de Entrega dos 
Brascom Ltda.

OBS:CASO CHEGO NO SPAM OU LIXO ENCAMINHA PRA CAIXA DE ENTRADA LINK DO CODIDO DE RASTREIAMENTO SERA LIBERADO OBRIGADO(A).
