### ISSUE TITLE
Chekout - e não faz o redirecionamento

### ISSUE THREAD

**Issue by diuliano0** [andrebian/cake-plugin-pagseguro#13]
Strict (2048): Declaration of PagSeguroComponent::startup() should be compatible with Component::startup(Controller $controller) [APP/Plugin/PagSeguro/Controller/Component/PagSeguroComponent.php, line 0]
Strict (2048): Declaration of CheckoutComponent::startup() should be compatible with PagSeguroComponent::startup($controller) [APP/Plugin/PagSeguro/Controller/Component/CheckoutComponent.php, line 0]
Strict (2048): Declaration of RetornoPagSeguroComponent::startup() should be compatible with PagSeguroComponent::startup($controller) [APP/Plugin/PagSeguro/Controller/Component/RetornoPagSeguroComponent.php, line 0]

**Comment by andrebian** [comment]
quer compartilhar o que você adicionou @diuliano0 ?

**Comment by diuliano0** [comment]
claro adoraria.






Enviado do Email do Windows





De: Andre Cardoso
Enviado: ‎quinta-feira‎, ‎1‎ de ‎janeiro‎ de ‎2015 ‎17‎:‎52
Para: andrebian/cake-plugin-pagseguro
Cc: diuliano0





quer compartilhar o que você adicionou @diuliano0 ?

**Comment by diuliano0** [comment]
Magazine Você
    
    

        
            
                Caso não esteja visualizando o e-mail, acesse esse link.
            
        
        
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                        
                                                    
                                                    
                                                        
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        

                        
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        

                                        
                                            
                                                Aproveite agora sua change de adquirir produtos mais barato não perca as super ofertas Magazine.
                                            
                                        
                                    
                                
                            
                        

                        
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        Impressora Jato de Tinta Colorida - HP Deskjet 1000 Bivolt
                                                    
                                                
                                            

                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    
                                                                                        
                                                                                            
                                                                                                de R$ 249,00
                                                                                            
                                                                                        
                                                                                        
                                                                                            
                                                                                                
                                                                                                    
                                                                                                        por
                                                                                                    
                                                                                                
                                                                                                
                                                                                                    
                                                                                                        219,00
                                                                                                    
                                                                                                
                                                                                            
                                                                                            
                                                                                                
                                                                                                    R$
                                                                                                
                                                                                            
                                                                                        

                                                                                        
                                                                                            
                                                                                                em até 10x de R$ 21,90
                                                                                                sem juros no cartão de crédito
                                                                                            
                                                                                            
                                                                                                ou R$ 186,15 à vista
                                                                                            
                                                                                        
                                                                                    
                                                                                
                                                                            
                                                                        
                                                                    
                                                                

                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Smartphone Nokia Lumia 630 Dual Chip 3G Câm. 5MP - Windows Phone Tela 4.5" Proc. Quad Core Tv Digital 
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 699,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 399,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 39,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 339,15 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Smartphone Motorola Moto G DTV Colors Dual Chip 3G - Android 4.4 Câm. 8MP Tela 5" Proc. Quad Core Wi-Fi 
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 899,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 879,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 87,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 747,15 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Smartphone Samsung Galaxy Gran Prime Duos TV Dual - Chip 3G Android 4.4 Câm. 8MP Tela 5" TV Digital 
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 879,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 849,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 84,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 721,65 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Smartphone Samsung Galaxy Gran Prime Duos TV Dual - Chip 3G Android 4.4 Câm. 8MP Tela 5" TV Digital 
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 899,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 849,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 84,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 721,65 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
            
        
        
    
        
            Como Funciona
            Dúvidas
            Fale Conosco
            Política de Privacidade
        
        
            
                2015 © Magazine Luiza
            
        
    
    
        
            
                Compre de quem você confia. Muito mais vantagens para você. O Magazine Você é um canal de vendas do Magazine Luiza.O remetente deste email está autorizado a vender nossos produtos através do site www.magazinevoce.com.br
            
            
                Preços anunciados não incluem frete. Este e-mail não deve ser respondido.
            
            
                Para dúvidas referentes a: entregas, montagens, cancelamentos e/ou pagamentos, entrar em contato com a Central de Atendimentoatravés do número 0800-344000.
            
            
                Para garantir o recebimento de nossos alertas e informativos, cadastre em seus contatos: emailcenter@magazinevoce.com.br.
                Se você não quiser mais receber nossos e-mails, descadastre-se.

**Comment by diuliano0** [comment]
Magazine Você
    
    

        
            
                Caso não esteja visualizando o e-mail, acesse esse link.
            
        
        
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                        
                                                    
                                                    
                                                        
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        

                        
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        

                                        
                                            
                                                Não perca as melhores ofertas Magazine.
                                            
                                        
                                    
                                
                            
                        

                        
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        Smartphone Motorola Moto G DTV Colors Dual Chip 3G - Android 4.4 Câm. 8MP Tela 5" Proc. Quad Core Wi-Fi 
                                                    
                                                
                                            

                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    
                                                                                        
                                                                                            
                                                                                                de R$ 899,00
                                                                                            
                                                                                        
                                                                                        
                                                                                            
                                                                                                
                                                                                                    
                                                                                                        por
                                                                                                    
                                                                                                
                                                                                                
                                                                                                    
                                                                                                        879,00
                                                                                                    
                                                                                                
                                                                                            
                                                                                            
                                                                                                
                                                                                                    R$
                                                                                                
                                                                                            
                                                                                        

                                                                                        
                                                                                            
                                                                                                em até 10x de R$ 87,90
                                                                                                sem juros no cartão de crédito
                                                                                            
                                                                                            
                                                                                                ou R$ 773,52 à vista
                                                                                            
                                                                                        
                                                                                    
                                                                                
                                                                            
                                                                        
                                                                    
                                                                

                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Ar Condicionado Split Samsung 12.000 BTUs Frio - AS12UWBUXAZ com Controle Remoto e Vírus Doctor 220 Volts
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 1.399,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 1.099,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 109,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 934,15 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Tablet LG G Pad 10 16GB Tela 10,1" Wi-Fi Android - 4.4 Processador Quad Core Câmera 5MP + Frontal Bivolt
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 1.099,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 849,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 84,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 721,65 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Tablet Samsung Galaxy Tab 3 Lite T111 8GB Tela 7" - 3G Wi-Fi Android 4.2 Proc. Dual Core Câm. 2MP GPS Bivolt
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 999,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 699,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 69,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 594,15 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Tablet Asus Fonepad 7 Dual Sim 8GB Tela 7" 3G - Wi-Fi Android 4.4 Proc Intel Dual Core Câm 2MP Bivolt
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 799,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 629,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 62,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 534,65 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
            
        
        
    
        
            Como Funciona
            Dúvidas
            Fale Conosco
            Política de Privacidade
        
        
            
                2015 © Magazine Luiza
            
        
    
    
        
            
                Compre de quem você confia. Muito mais vantagens para você. O Magazine Você é um canal de vendas do Magazine Luiza.O remetente deste email está autorizado a vender nossos produtos através do site www.magazinevoce.com.br
            
            
                Preços anunciados não incluem frete. Este e-mail não deve ser respondido.
            
            
                Para dúvidas referentes a: entregas, montagens, cancelamentos e/ou pagamentos, entrar em contato com a Central de Atendimentoatravés do número 0800-344000.
            
            
                Para garantir o recebimento de nossos alertas e informativos, cadastre em seus contatos: emailcenter@magazinevoce.com.br.
                Se você não quiser mais receber nossos e-mails, descadastre-se.

**Comment by diuliano0** [comment]
Magazine Você
    
    

        
            
                Caso não esteja visualizando o e-mail, acesse esse link.
            
        
        
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                        
                                                    
                                                    
                                                        
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        

                        
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        

                                        
                                            
                                                Comprar Barato é ótimo então o Magazine Luíza quer ajudar a levantar suas expectativas.
                                            
                                        
                                    
                                
                            
                        

                        
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        Ar Condicionado Split LG 7500 BTUs Frio Smile - TS-C072YNW5 On/Off com Controle Remoto e Filtro 3M 220 Volts
                                                    
                                                
                                            

                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    
                                                                                        
                                                                                            
                                                                                                de R$ 1.359,00
                                                                                            
                                                                                        
                                                                                        
                                                                                            
                                                                                                
                                                                                                    
                                                                                                        por
                                                                                                    
                                                                                                
                                                                                                
                                                                                                    
                                                                                                        1.099,00
                                                                                                    
                                                                                                
                                                                                            
                                                                                            
                                                                                                
                                                                                                    R$
                                                                                                
                                                                                            
                                                                                        

                                                                                        
                                                                                            
                                                                                                em até 10x de R$ 109,90
                                                                                                sem juros no cartão de crédito
                                                                                            
                                                                                            
                                                                                                ou R$ 934,15 à vista
                                                                                            
                                                                                        
                                                                                    
                                                                                
                                                                            
                                                                        
                                                                    
                                                                

                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Micro-ondas Brastemp BMA30 30L - com Painel Digital 110 Volts
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 499,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 439,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 43,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 417,05 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Relógio Monitor Cardíaco HR102 Oregon com Alarme - Temporizador + Clipe para Bicicleta 
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 199,90
                                                                        
                                                                    
                                                                    
                                                                        por R$ 99,90
                                                                    
                                                                    
                                                                        
                                                                            em até 4x de R$ 24,98 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Tablet Asus Fonepad 7 Dual Sim 8GB Tela 7" 3G - Wi-Fi Android 4.4 Proc Intel Dual Core Câm 2MP Bivolt
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 799,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 629,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 62,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 534,65 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                            
                                                                
                                                                    Smartphone Samsung Galaxy Gran Prime Duos TV Dual - Chip 3G Android 4.4 Câm. 8MP Tela 5" TV Digital 
                                                                
                                                                
                                                                    
                                                                        
                                                                            De R$ 879,00
                                                                        
                                                                    
                                                                    
                                                                        por R$ 849,00
                                                                    
                                                                    
                                                                        
                                                                            em até 10x de R$ 84,90 sem juros no cartão de crédito
                                                                        
                                                                        
                                                                            ou R$ 721,65 à vista
                                                                        
                                                                    
                                                                    
                                                                        
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
            
        
        
    
        
            Como Funciona
            Dúvidas
            Fale Conosco
            Política de Privacidade
        
        
            
                2015 © Magazine Luiza
            
        
    
    
        
            
                Compre de quem você confia. Muito mais vantagens para você. O Magazine Você é um canal de vendas do Magazine Luiza.O remetente deste email está autorizado a vender nossos produtos através do site www.magazinevoce.com.br
            
            
                Preços anunciados não incluem frete. Este e-mail não deve ser respondido.
            
            
                Para dúvidas referentes a: entregas, montagens, cancelamentos e/ou pagamentos, entrar em contato com a Central de Atendimentoatravés do número 0800-344000.
            
            
                Para garantir o recebimento de nossos alertas e informativos, cadastre em seus contatos: emailcenter@magazinevoce.com.br.
                Se você não quiser mais receber nossos e-mails, descadastre-se.
