### ISSUE TITLE
Duvida Instação do Plugin PagSeguro

### ISSUE THREAD

**Issue by viniciusnm** [andrebian/cake-plugin-pagseguro#14]
Olá primeiramente gostaria de parbenizá-lo pela iniciativa...

Porém estou tendo um erro durante a instalação do Plugin. Segui os paços descritos no tutorial de instalação, também utilizei o composer como recomendado. Estou utilizando o plugin em outro onde tenho cadastros de clientes etc.. 
Criei uma controller e estou carregando o componente 
public $components = array('PagSeguro.Carrinho');
Mas ocorre o seguinte erro
 Error: require_once() [<a href='http://php.net/function.require'>function.require</a>]: Failed opening required '/home/start/www/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear')
File: /home/start/www/imobisystem/Plugin/PagSeguro/Controller/Component/CarrinhoComponent.php 

Pelo que pude ver o erro é ao incluir os seguintes arquivos
require_once ROOT . '/vendor/autoload.php';
require_once ROOT . '/vendor/pagseguro/php/source/PagSeguroLibrary/PagSeguroLibrary.php';
require_once ROOT . '/app/Plugin/PagSeguro/Assets/Codes.php';

Substituindo o require_once pelo código a seguir consegui eliminar o erro!
App::uses('autoload.php', 'Vendor');
App::uses('pagseguro/php/source/PagSeguroLibrary/PagSeguroLibrary.php', 'Vendor');
App::uses('Plugin/PagSeguro/Assets/Codes.php', 'Plugin');

O próximo erro foi 
Notice (8): Undefined index: credenciais [APP/Plugin/PagSeguro/Controller/Component/CarrinhoComponent.php, line 56]
Mas não entendi pois alterei as credenciais no bootstrap como recomendado, também setei direto na controller onde carrego o component "PagSeguro.Carrinho" e nada.
Outro detalhe que não entendi foi fato de carregar
 "A utilização do 'PagSeguro.PagSeguro' NÃO deve ser ignorada.", pois não encontrei este arquivo.

Desculpe as tantas perguntas, pois sou novo no Cake. 

Obrigado! Abraço!

**Comment by andrebian** [comment]
Olá, é bem estranho ele não reconhecer o vendor do composer sendo o mesmo instalado pelo gerenciador. Teria como verificar se a pasta "vendor" existe e você tem permissão de leitura nela?

O segundo ponto é sugiro você utilizar o PagSeguro.Checkout ao invés de PagSeguro.Carrrinho. O motivo da troca foi que o nome Carrinho não fazia sentido, pois o que ele faz ao chegar neste ponto é o checkout em si, ou seja a finalização da compra de fato. 

por não ter encontrado o arquivo PagSeguro.PagSeguro talvez seja por você ter baixado o mesmo antes de eu o adicionar e ler a documentação atualizada. Sugiro dar um composer update para obter a nova versão. Se ainda continuar vindo a versão 2.0.3 para você force a versão no arquivo composer.json "require": {"andrebian/pag_seguro": "2.1"}.

Com relação às credenciais faltantes é porque por questão de compatibilidade eu mantive todos os métodos antigos para que um update não quebrasse. Com isso todos os métodos do PagSeguro.Carrinho foram anotados como @deprecated e sugeridos a utilizar os métodos equivalentes do PagSeguro.Checkout. Veja na versão 2.0.3 como era a configuração no bootstrap: https://github.com/andrebian/cake-plugin-pagseguro/blob/0e6b8e45bb0ca4d6b8558bbb3971549fff71cea6/Exemplos/Config/bootstrap.php

**Comment by viniciusnm** [comment]
Sim a pasta Vendor tem permissão de leitura tenho o Cake ver 2.6.0 instalado via composer na Vendor. Tenho o sistema dividido em vários Plugins por ex.: Admin (Autenticação), Public (Visitantes), Restric (Area Interna) "PagSeguro" ...
Estou tentando usar os "Components" do Plugin "PagSeguro" no Plugin "Restrict".

Utilizei a versão  "andrebian/pag_seguro": "2.0.0", vou tentar a 2.1 e seguir tuas dicas.

Só mais uma dúvida. Esse plugin depende de certificado SSL para rodar??

Vou realizar mais uns testes e entro em contado em breve para avisar o que aconteceu..
Obg pelas dicas.
At.

**Comment by viniciusnm** [comment]
Outro detalhe é a forma que criei o projeto. Primeiramente baixei o CakePHP, após as configurações de permissões e etc, acessei  "cd cakephp/lib/Cake/Console" depois "./cake bake". Depois disso ele pede o local onde deseja salvar o projeto e outras configurações como DB...
Com isso ele cria o projeto com a seguinte estrutura:
-Config
-Console
-Controller
-index.php
-Lib
-Locale
-Model
-Plugin
-Test
-tmp
-Vendor 
-View
-webroot
Note que desta forma o projeto não fica dentro de App, como é o caso padrão. 
Logo baixei o cakephp via composer para Vendor e alterei a "index" na webroot apontando para Vendor, para ele utilizar o cake que agora está na Vendor:
//Apontando diretório para Vendor
define(
    'CAKE_CORE_INCLUDE_PATH',
    ROOT . DS . APP_DIR . DS . 'Vendor' . DS . 'cakephp' . DS . 'cakephp' . DS . 'lib'
);
E assim tenho diverso Plugins tudo funcionando ok.
Instalei a verssão "andrebian/pag_seguro": "2.1", como você recomendou, o problema agora é que da o seguinte erro 
O autoload.php não está presente, isto quer dizer que o composer pode não estar instalado. Visite https://getcomposer.org e saiba mais. Caso o composer esteja instalado pode ser que ele não esteja alocando seus arquivos na pasta "vendor(s)" 

-OBS: O composer tá 100%, só ele tá procurando no local errado!

Talvez ele esteja procurando o plugin "PagSeguro" na App/Plugin e não diretamente na "Plugin" como estou utilizando.

**Comment by andrebian** [comment]
@viniciusnm fiz a instalação semelhante à sua e de fato deu o mesmo erro. Já o corrigi na versão 2.1.1, atualize seu composer.json pra "andrebian/pag_seguro": "2.1.1" e o problema estará resolvido. https://github.com/andrebian/cake-plugin-pagseguro/blob/62c2cf79c71a24559e30eb81103f54d2e0fec38b/Controller/Component/PagSeguroComponent.php#L24-L44

O que fiz foi verificar caso o desenvolvedor setou outro diretório para o vendor, como foi o seu caso. Com isso sempre ele procurará por padrão em vendor/ mas se estiver definido lib/ por exemplo o autoload.php será buscado em lib.

**Comment by andrebian** [comment]
Segue print da estrutura de meu projeto, ao lado o esquema do composer pelo qual defini o vendor semelhante ao seu caso e que funcionou.
![estrutura](https://cloud.githubusercontent.com/assets/2091739/5604126/b00cbb60-938f-11e4-8edc-2df90853c71d.png)

A imagem abaixo mostra o endereço de redirecionamento ao PagSeguro mostrando o correto funcionamento do plugin.
![realizando-chamada](https://cloud.githubusercontent.com/assets/2091739/5604129/cc0c9218-938f-11e4-9724-3330764eeabd.png)

**Comment by andrebian** [comment]
Por gentileza confirma se funcionou para eu poder fechar a issue.

**Comment by viniciusnm** [comment]
Olá!
Realizei os testes e continuou dando o mesmo erro, o problema acontece quando o projeto é gerado pelo cake bake como é o caso. Notei no arquivo ConsultaComponent, como em outros a inclusão de arquivos como esse
 require_once ROOT . '/app/Plugin/PagSeguro/Assets/Codes.php';
Porém quando crio o projeto via Bake ele não cria aquelas pastas 
-App, -lib, -Plugins e -vendors, que estão na raiz do cake, ele já cria direto as pastas como lhe mostrei no terceiro comentário.
O projeto criado pelo bake, utiliza, pelo que pude ver, somente os arquivos que estão dentro da App. 

Tentei mudar require_once ROOT . '/app/Plugin/PagSeguro/Assets/Codes.php';
para require_once ROOT . '/Plugin/PagSeguro/Assets/Codes.php'; Mas não deu deve ter mais alguns detalhes. Estou pensando em recriar o projeto com o cake tradicional sem a utilização do bake.

**Comment by andrebian** [comment]
Assim, realizando a instalação pelo bake é possível seguir a estrutura padrão do Cake e sua aplicação ficar em app/ e o core do Cake em lib/. Neste caso percebi que você optou por instalar o cake em um local diferente de sua estrutura padrão e recomendada. Sugiro ver este video que fiz há um tempo sobre a instalação via bake: https://www.youtube.com/watch?v=F0g0db268-c

Outro ponto é que você está utilizando o componente PagSeguro.Consulta, ele realmente se faz necessário no momento que você está utilizando? Pergunto isso porque se for pra tratar o retorno do PagSeguro após uma compra o componente PagSeguro.Retorno resolve. O Consulta tem hoje o único diferencial com relação ao Retorno que pode buscar a lista de transações de um período de tempo (1 mês).

**Comment by viniciusnm** [comment]
Beleza, muito legal essa forma de instalação. Agora funcionou.
Quanto ao PagSeguro.Consulta, utilizei somente como exemplo, para te mostrar o "require_once".

Só mais uma pergunta: é possível gerar o boleto de forma transparente, como "createTransactionUsingBoleto"

No php puro, através do exemplo disponibilizado pelo PagSeguro, consegui fazer com segue o link abaixo.
http://infoarts.vv.si/pag-seguro/php-2.3.0/source/examples/createTransactionUsingBoleto.php

**Comment by andrebian** [comment]
@viniciusnm a questão do checkout transparente ainda não comecei a integrar, existe inclusive uma issue sobre isso (#12). Em breve estarei trabalhando nesta integração, este mês ainda, apesar de todas as correrias. 

Vou fechar esta issue, nos conversamos na issue #12?
