### ISSUE TITLE
Suporte a diferentes APP_DIR

### ISSUE THREAD

**Issue by Cayan** [andrebian/cake-plugin-pagseguro#16]
Como o título já esclarece, seria bacana se este plugin tivesse suporte a diferentes APP_DIR.

**Comment by andrebian** [comment]
Tem um exemplo? o APP_DIR é a constante que o cake cria informando onde está a aplicação, seja em / ou em /app.

**Comment by Cayan** [comment]
https://github.com/andrebian/cake-plugin-pagseguro/pull/20

**Comment by hernandes** [comment]
Estou com o mesmo problema do @Cayan, a solução do pull dele resolve, @andrebian, poderia fazer um merge com a atualização?
