### ISSUE TITLE
Configurações

### ISSUE THREAD

**Issue by Cayan** [andrebian/cake-plugin-pagseguro#17]
De acordo com o README existem duas possibilidades para se configurar as credenciais, contudo, caso nada seja preenchido quando o Plugin for carregado, este irá gerar uma exceção (como visto na linha 67 do arquivo PagSeguroComponent.php).

Como as minhas configurações são dinamicamente carregadas pelo banco de dados, para contornar a situação, segue minha solução:

    Configure::write('PagSeguro', array(
        'email' => Configure::read('Payment.PagSeguro.Email'),
        'token' => Configure::read('Payment.PagSeguro.Token'),
        'isSandbox' => Configure::read('Payment.PagSeguro.isSandbox')
    ));
    
    $this->PagSeguro = $this->Components->load('PagSeguro.PagSeguro');
    $this->Checkout = $this->Components->load('PagSeguro.Checkout');
    $this->Retorno = $this->Components->load('PagSeguro.Retorno');
    
    $this->PagSeguro->initialize($this);
    $this->Checkout->initialize($this);
    $this->Retorno->initialize($this);
    
    $this->PagSeguro->startup($this);
    $this->Checkout->startup($this);
    $this->Retorno->startup($this);

**Comment by andrebian** [comment]
Na verdade não estruturei o plugin para suportar o carregamento on-the-fly. Tente utilizar os componentes conforme a documentação que funciona corretamente. https://github.com/andrebian/cake-plugin-pagseguro/blob/master/Exemplos/Controller/ComprasController.php.

Não entendo a necessidade de carregar os componentes on-the-fly... é pra evitar o sobrecarregamento? Se sim poderia pensar em deixar o controller mais enxuto. Eu sempre separo um controller somente para fazer a finalização da compra, com isso um `public $components = array('Componente'); ` sempre resolve meu problema.

**Comment by Cayan** [comment]
Como expliquei no outro issue, já que você puxou o assunto lá.

O motivo deu ter utilizado o carregamento on-the-fly é porque o seu Plugin exige que as configurações de e-mail e token tenham sido realizadas (o que não está de acordo com o README).

No meu projeto, carrego o e-mail e o token por banco de dados, portanto, ajustar estas opções no arquivos bootstrap.php (como sugerido) é inviável. 

Outro motivo da sugestão do carregamento on-the-fly é porque quis fazer minha aplicação funcionar sendo o menos invasivo possível em seu Plugin, tendo em vista que a correção para a exigência das configurações ser simples.
