### ISSUE TITLE
NotificacaoComponent::$credenciais, como resolver?

### ISSUE THREAD

**Issue by recoverjp** [andrebian/cake-plugin-pagseguro#22]
Error: Access level to NotificacaoComponent::$credenciais must be protected (as in class PagSeguroComponent) or weaker	
File: C:\XAMPP\htdocs\projeto\app\Plugin\PagSeguro\Controller\Component\NotificacaoComponent.php	
Line: 235

Não sei o porquê de estar dando isso...

**Comment by andrebian** [comment]
Sabe me dizer qual a versão vc está usando? Pode ver no README do seu plugin. Atualmente a linha 235 nem existe mais. Desde já sugiro você atualizar, de preferência pra "dev-master" que estou sempre evoluindo conforme o feedback dos desenvolvedores.

**Comment by recoverjp** [comment]
# PAGSEGURO PLUGIN
_v 2.1.1_

Pode me dar um help nessa atualização? Como faço?

**Comment by recoverjp** [comment]
Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for andrebian/pag_seguro dev-master -> satisfiable by
 andrebian/pag_seguro[dev-master].
    - andrebian/pag_seguro dev-master requires pagseguro/php dev-desenvolvimento
 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.

**Comment by andrebian** [comment]
Se está utilizando pelo composer conforme eu recomendei muda no teu `composer.json` de 

```json
{
    "require": {
        "andrebian/pag_seguro": "2.1.1"
    }
}
```

pra


```json
{
    "require": {
        "andrebian/pag_seguro": "dev-master"
    }
}
```

No entanto vasculhando o código aqui localizei o erro, ja posto aqui.

**Comment by andrebian** [comment]
Com relação ao erro que postou, a solução tá aqui: https://github.com/andrebian/cake-plugin-pagseguro/blob/master/README.md#erro-comum

**Comment by andrebian** [comment]
A correção para o erro inicial se dá nestes dois commits 349aed0a2c9e26b1ad75576ac377aee00880ef46 e faede2b1b1f792b05def4f773cb9c5a8f4eb20bd

**Comment by andrebian** [comment]
Pelo que testei aqui foi tranquilo, só o PagSeguro pra variar tá zoando em sua API... vou ver se corrijo e mando um Pull Request pra eles.

![erro-ps](https://cloud.githubusercontent.com/assets/2091739/5830977/e80dc17a-a10f-11e4-82a6-587a5921a200.png)

Se funcionou pra vc também por gentileza me avisa pra eu fechar esta issue.

**Comment by andrebian** [comment]
Prontinho, se eles vão aceitar já não sei... https://github.com/pagseguro/php/pull/21

**Comment by andrebian** [comment]
Correção: https://github.com/pagseguro/php/pull/21
