### ISSUE TITLE
Problema com plugin

### ISSUE THREAD

**Issue by whera** [andrebian/cake-plugin-pagseguro#23]
O plugin esta funcionando perfeitamente até uns dias atrás

agora o mesmo esta me apresentando o seguinte

Strict (2048): Non-static method PagSeguroConfigWrapper::getEnvironment() should not be called statically [APP/Vendor/pagseguro/php/source/PagSeguroLibrary/config/PagSeguroConfigWrapper.php, line 80]
Strict (2048): Non-static method PagSeguroConfigWrapper::getCredentials() should not be called statically [APP/Vendor/pagseguro/php/source/PagSeguroLibrary/config/PagSeguroConfigWrapper.php, line 81]
Strict (2048): Non-static method PagSeguroConfigWrapper::getApplicationEncoding() should not be called statically [APP/Vendor/pagseguro/php/source/PagSeguroLibrary/config/PagSeguroConfigWrapper.php, line 82]
Strict (2048): Non-static method PagSeguroConfigWrapper::getLogConfig() should not be called statically [APP/Vendor/pagseguro/php/source/PagSeguroLibrary/config/PagSeguroConfigWrapper.php, line 83]

**Comment by erickhaendel** [comment]
Aconteceu o mesmo comigo, os métodos não estavam estaticos... alterei eles, e ta funcionando.

**Comment by gustavocp** [comment]
Aconteceu comigo também, segui a dica do @erickhaendel  e funcionou

**Comment by andrebian** [comment]
Eu corrigi uma destas chamadas e enviei ao PagSeguo (https://github.com/pagseguro/php/pull/21/files), como vocês também fizeram isso sugiro enviar Pull Requests a eles também, assim o erro é corrigido diretamente na fonte.

**Comment by andrebian** [comment]
@whera o PagSeguro aceitou meu Pull Request, ainda com o problema? Se sim, por gentileza atualiza pelo composer pra ver se corrigiu...
